### ISSUE TITLE
Python module not working anymore

### ISSUE THREAD

**Issue by hemarkus** [QMSTR/qmstr-all#126]
```
2018/09/25 09:21:02 pyqmstr-spdx-analyzer failed with:
	--> Traceback (most recent call last):
	-->   File ".bootstrap/_pex/pex.py", line 351, in execute
	-->   File ".bootstrap/_pex/pex.py", line 281, in _wrap_coverage
	-->   File ".bootstrap/_pex/pex.py", line 313, in _wrap_profiling
	-->   File ".bootstrap/_pex/pex.py", line 394, in _execute
	-->   File ".bootstrap/_pex/pex.py", line 491, in execute_entry
	-->   File ".bootstrap/_pex/pex.py", line 509, in execute_pkg_resources
	-->   File ".bootstrap/pkg_resources/__init__.py", line 2330, in resolve
	-->   File "/home/qmstr/.pex/install/pyqmstr_spdx_analyzer-0.2-py2-none-any.whl.f908e7c81f69812dc0d8d528afcfc407a843922d/pyqmstr_spdx_analyzer-0.2-py2-none-any.whl/spdxanalyzer/__main__.py", line 6, in <module>
	-->     from pyqmstr.module.module import QMSTR_Analyzer
	-->   File "/home/qmstr/.pex/install/pyqmstr-0.2-py2-none-any.whl.c16facc9e5b464b84c334ea863ac73b4492d356b/pyqmstr-0.2-py2-none-any.whl/pyqmstr/module/module.py", line 1, in <module>
	-->     import grpc
	-->   File "/home/qmstr/.pex/install/grpcio-1.11.0-cp27-cp27mu-manylinux1_x86_64.whl.1b618e2fe5f9d1bce1ff32fc18b22aca7855516a/grpcio-1.11.0-cp27-cp27mu-manylinux1_x86_64.whl/grpc/__init__.py", line 22, in <module>
	-->     from grpc._cython import cygrpc as _cygrpc
	-->   File "src/python/grpcio/grpc/_cython/cygrpc.pyx", line 18, in init grpc._cython.cygrpc
	-->   File "/home/qmstr/.pex/install/setuptools-40.4.3-py2.py3-none-any.whl.2a195c3ab69b2327784ba2ff2f549025346caab5/setuptools-40.4.3-py2.py3-none-any.whl/pkg_resources/__init__.py", line 77, in <module>
	-->     from . import py31compat
	--> ImportError: cannot import name py31compat
```

**Comment by hemarkus** [comment]
This is probably a py2 vs. py3 problem.
